### ISSUE TITLE
Failures in the BZCommenter can generates multiple BZ comments

### ISSUE THREAD

**Issue by dclarizio** [ManageIQ/miq_bot#108] opened 2015-08-20 22:59 UTC
On this example, a single merge caused 2 comments to be added, 8 times each, for a total of 16 comments.  I think it is supposed to be 2, one for the original commit and one for the merge commit.
https://bugzilla.redhat.com/show_bug.cgi?id=1253804

**Comment by dclarizio** [comment] 2015-08-24 13:59
Here's another one with a whole bunch of repeated comments:
https://bugzilla.redhat.com/show_bug.cgi?id=1243497

**Comment by blomquisg** [comment] 2015-08-24 16:06
Me too: https://bugzilla.redhat.com/show_bug.cgi?id=1211730

**Comment by Fryguy** [comment] 2015-08-31 21:51
Good idea.  This kind of goes along with #81.  The problem is that the default message on GitLab is to include the commit's messages (including BZ URLs).

**Comment by Fryguy** [comment] 2015-08-31 21:54
Oh wait, the repeated BZ message you are seeing is not because it's a merge commit...The repeated BZ messages were because the bot would write to BZ, then run out of memory before it marked the work as completed, which caused it to be retried.

So, this is not really related to merge commits at all.

However as per #81, my question is... @dclarizio Should we be writing two messages?  Do you want to see the merge commit on BZ?

**Comment by dclarizio** [comment] 2015-08-31 22:32
@Fryguy I'm not sure . . . I guess it could be of value having them both.  Certainly having 2 rather than 16 would be better. :)

**Comment by Fryguy** [comment] 2015-09-01 17:30
:D  Yeah, on that I just need to find a way to reorder the operations so we don't comment, then fail...we should fail before we comment.

**Comment by Fryguy** [comment] 2021-09-30 16:23
Closing since BZ commenter was removed in #569

**Closed by Fryguy** 2021-09-30 16:23 UTC
Labels: bug, help wanted, pinned
