### ISSUE TITLE
Ability to add_reviewer/remove_reviewer

### ISSUE THREAD

**Issue by blomquisg** [ManageIQ/miq_bot#352] opened 2017-07-10 18:00 UTC
Now that Github has reviewers, let's allow miq_bot to add and remove reviewers.

Proposal:

```
@miq-bot add_reviewer @blomquisg
    >> `@blomquisg` is added to the list of reviewers for the PR.
```

```
@miq-bot remove_reviewer @blomquisg
    >> `@blomquisg` is removed from the list of reviewers for the PR. 
```

**Comment by Fryguy** [comment] 2017-07-11 15:37
Is thought the author of a PR can ask for whomever they want to review?

**Comment by Fryguy** [comment] 2017-07-11 15:38
Duplicate of #337

**Closed by Fryguy** 2017-07-11 15:38 UTC
