### ISSUE TITLE
command to move issue from one repo to another

### ISSUE THREAD

**Issue by dajohnso** [ManageIQ/miq_bot#272] opened 2017-01-27 00:37 UTC
For instance, now that the ui's are factored out and in their own repo, a command to "copy" the issue to the other repo and provide a link, close the original ticket, etc would make it easier

**Comment by bdunne** [comment] 2017-02-02 19:46
Marking as duplicate of #258 
@dajohnso If you think it isn't a duplicate or if #258 doesn't meet your requirements, please update or reopen as necessary.

**Closed by bdunne** 2017-02-02 19:46 UTC
Labels: enhancement
