### ISSUE TITLE
Add ability to enable / disable check on a per repo basis

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#356] opened 2017-07-31 15:44 UTC
On the SUI repo the BOT is checking with ruby 2.2.6, rubocop 0.47.1, and haml-lint 0.20.0, this is unnecessary considering there is no Ruby in the repo (no sense in wasting cycles)

**Comment by Fryguy** [comment] 2017-07-31 16:17
This is mostly a duplicate of https://github.com/ManageIQ/miq_bot/issues/244, so I'm marking it as such

**Closed by Fryguy** 2017-07-31 16:17 UTC
