### ISSUE TITLE
sync [WIP] in title with "wip" label

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#247] opened 2017-01-06 19:43 UTC
If a title contains [WIP] the bot should add the "wip" label automagically and vice versa if they "wip" label is added the title should be prefixed with [WIP].

The inverse as well, if [WIP] is removed then remove the label (etc).

**Comment by Fryguy** [comment] 2017-01-06 22:45
duplicate of #34 , and also partially implemented in #220

**Closed by Fryguy** 2017-01-06 22:45 UTC
