### ISSUE TITLE
RFE:  @miq-bot add_reviewer @username

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/miq_bot#354] opened 2017-07-25 15:33 UTC
Feature:
--------
Add a command to the bot to allow users to request a review from a particular individual.  Possible aliases suggestions:

* `@miq-bot review @username`
* `@miq-bot request_review @username`
* `@miq-bot please_review @username`

**Comment by chriskacerguis** [comment] 2017-07-25 15:37
Question...should there be some kind of inverse for this?

```@miq-bot remove_review @username```
```@miq-bot un_review @username``` ???

**Comment by Fryguy** [comment] 2017-07-25 15:45
Duplicate of #337

**Closed by Fryguy** 2017-07-25 15:45 UTC

**Comment by NickLaMuro** [comment] 2017-07-25 15:49
@Fryguy my bad.  Didn't take a second to check the open issues...
