### ISSUE TITLE
non-master branch prefix

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#248] opened 2017-01-06 19:45 UTC
If the PR is to a branch other than master (e.g. euwe) then the title should be check that it contains the prefix [BRANCH], if not it should update that.

**Comment by Fryguy** [comment] 2017-01-06 22:45
Completed in #219 (waiting for deploy)

**Comment by Fryguy** [comment] 2017-01-06 22:46
Also happens to be a duplicate of #174

**Closed by Fryguy** 2017-01-06 22:45 UTC
